# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        # Définir des valeurs pour les paramètres de type primitif (chaîne, nombre, booléen)
        # Ces valeurs seront utilisées pour tout service déclarant ces paramètres.
        bind:
            string $country: '%env(APP_COUNTRY)%'
            string $noReply: 'no-reply@example.com'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration manuelle, en général, c'est non-nécessaire
    # La clé de premier niveau sert d'identifiant du service
    # Si l'identifiant est le FQCN (nom de classe pleinement qualifié)
    # Une partie de la configuration possible sera déjà géré automatiquement
    # La déclaration explicite sert par exemple pour définir un passage de paramètre
    # qui n'est pas un autre service
    App\Service\Calendar:
        class: App\Service\Calendar
        arguments:
            $country: '%env(APP_COUNTRY)%'
